spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-xsl-dev
---
spring:
    profiles: test
    application:
        name: microservicecloud-config-xsl-test